const test = [
  {
    id: 22,
    title: 'Product 22 Clothing',
    category: 'Clothing',
    rating: 2,
    reviews: 55,
    prime: true,
    price: 266.57,
    relativePath: '/thumbnail/img/22',
  },
  {
    id: 31,
    title: 'Product 31 Clothing',
    category: 'Clothing',
    rating: 4,
    reviews: 251,
    prime: true,
    price: 58.27,
    relativePath: '/thumbnail/img/31',
  },
  {
    id: 67,
    title: 'Product 67 Clothing',
    category: 'Clothing',
    rating: 1,
    reviews: 41,
    prime: true,
    price: 118.16,
    relativePath: '/thumbnail/img/67',
  },
  {
    id: 74,
    title: 'Product 74 Clothing',
    category: 'Clothing',
    rating: 4,
    reviews: 241,
    prime: true,
    price: 371.14,
    relativePath: '/thumbnail/img/74',
  },
  {
    id: 80,
    title: 'Product 80 Clothing',
    category: 'Clothing',
    rating: 3,
    reviews: 119,
    prime: true,
    price: 194.63,
    relativePath: '/thumbnail/img/80',
  },
  {
    id: 101,
    title: 'Product 101 Clothing',
    category: 'Clothing',
    rating: 3,
    reviews: 117,
    prime: true,
    price: 74.02,
    relativePath: '/thumbnail/img/101',
  },
  {
    id: 119,
    title: 'Product 119 Clothing',
    category: 'Clothing',
    rating: 3,
    reviews: 86,
    prime: false,
    price: 194.92,
    relativePath: '/thumbnail/img/119',
  },
  {
    id: 127,
    title: 'Product 127 Clothing',
    category: 'Clothing',
    rating: 5,
    reviews: 149,
    prime: true,
    price: 166.85,
    relativePath: '/thumbnail/img/127',
  },
  {
    id: 143,
    title: 'Product 143 Clothing',
    category: 'Clothing',
    rating: 2,
    reviews: 143,
    prime: true,
    price: 388.24,
    relativePath: '/thumbnail/img/143',
  },
  {
    id: 149,
    title: 'Product 149 Clothing',
    category: 'Clothing',
    rating: 2,
    reviews: 33,
    prime: true,
    price: 225.91,
    relativePath: '/thumbnail/img/149',
  },
  {
    id: 179,
    title: 'Product 179 Clothing',
    category: 'Clothing',
    rating: 5,
    reviews: 175,
    prime: true,
    price: 166.76,
    relativePath: '/thumbnail/img/179',
  },
  {
    id: 184,
    title: 'Product 184 Clothing',
    category: 'Clothing',
    rating: 4,
    reviews: 160,
    prime: false,
    price: 349.42,
    relativePath: '/thumbnail/img/184',
  },
  {
    id: 185,
    title: 'Product 185 Clothing',
    category: 'Clothing',
    rating: 5,
    reviews: 107,
    prime: true,
    price: 197.47,
    relativePath: '/thumbnail/img/185',
  },
  {
    id: 193,
    title: 'Product 193 Clothing',
    category: 'Clothing',
    rating: 5,
    reviews: 137,
    prime: true,
    price: 137.72,
    relativePath: '/thumbnail/img/193',
  },
  {
    id: 201,
    title: 'Product 201 Clothing',
    category: 'Clothing',
    rating: 1,
    reviews: 190,
    prime: true,
    price: 396.16,
    relativePath: '/thumbnail/img/201',
  },
  {
    id: 204,
    title: 'Product 204 Clothing',
    category: 'Clothing',
    rating: 4,
    reviews: 106,
    prime: true,
    price: 132.17,
    relativePath: '/thumbnail/img/204',
  },
  {
    id: 230,
    title: 'Product 230 Clothing',
    category: 'Clothing',
    rating: 2,
    reviews: 126,
    prime: true,
    price: 350.33,
    relativePath: '/thumbnail/img/230',
  },
  {
    id: 235,
    title: 'Product 235 Clothing',
    category: 'Clothing',
    rating: 2,
    reviews: 93,
    prime: true,
    price: 32.43,
    relativePath: '/thumbnail/img/235',
  },
  {
    id: 236,
    title: 'Product 236 Clothing',
    category: 'Clothing',
    rating: 4,
    reviews: 58,
    prime: true,
    price: 203.46,
    relativePath: '/thumbnail/img/236',
  },
  {
    id: 255,
    title: 'Product 255 Clothing',
    category: 'Clothing',
    rating: 4,
    reviews: 86,
    prime: true,
    price: 356.76,
    relativePath: '/thumbnail/img/255',
  },
  {
    id: 275,
    title: 'Product 275 Clothing',
    category: 'Clothing',
    rating: 4,
    reviews: 139,
    prime: true,
    price: 120.06,
    relativePath: '/thumbnail/img/275',
  },
  {
    id: 281,
    title: 'Product 281 Clothing',
    category: 'Clothing',
    rating: 5,
    reviews: 132,
    prime: true,
    price: 275.53,
    relativePath: '/thumbnail/img/281',
  },
  {
    id: 285,
    title: 'Product 285 Clothing',
    category: 'Clothing',
    rating: 3,
    reviews: 211,
    prime: true,
    price: 213.42,
    relativePath: '/thumbnail/img/285',
  },
  {
    id: 287,
    title: 'Product 287 Clothing',
    category: 'Clothing',
    rating: 1,
    reviews: 40,
    prime: true,
    price: 43.65,
    relativePath: '/thumbnail/img/287',
  },
  {
    id: 296,
    title: 'Product 296 Clothing',
    category: 'Clothing',
    rating: 1,
    reviews: 211,
    prime: true,
    price: 26.95,
    relativePath: '/thumbnail/img/296',
  },
];

export default test;
